deploy: more debug in remote script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -16,10 +16,10 @@ fi
 site_dir="/var/www/www.popclip.app"
 
 # check that the git repo is clean
-if [ -n "$(git status --porcelain)" ]; then
-    echo "Error: git repo is not clean"
-    exit 1
-fi
+# if [ -n "$(git status --porcelain)" ]; then
+#     echo "Error: git repo is not clean"
+#     exit 1
+# fi
 
 # we use the git commit hash to generate a unique folder name
 id="g$(git rev-parse HEAD | cut -c 1-11)"
@@ -27,13 +27,29 @@ id="g$(git rev-parse HEAD | cut -c 1-11)"
 # the full destination path
 dest="${SSH_USER}@${SSH_HOST}:$site_dir/${id}"
 echo "Sending files to ${dest}"
-rsync -avzc "${src}/" "${dest}"
+#rsync -avzc "${src}/" "${dest}"
 
-# send the remove_old script
-rsync -avzc ./remove_old "${site_dir}"
+# complete the deployment on the server
+ssh ${SSH_USER}@${SSH_HOST} 'bash -s' <<END_SCRIPT
+set -e
+echo "In remote script"
 
-# symlink the new folder so it gets served
+cd ${site_dir}
+echo p \$(pwd)"
+
 echo "Updating symlink"
-ssh ${SSH_USER}@${SSH_HOST} "cd ${site_dir} && ln -sfn ${id} static && bash remove_old"
+ln -sfn ${id} static
+
+#echo "Removing old deployments"
+# Remove all but the newest n deployment directories
+# List directories sorted by modification time and skip the first n
+#ls -dt g*/
+#for dir in \$(ls -dt g*/ | tail -n +4); do
+#  echo "removing \$dir"
+#  #rm -rf "\$dir"
+#done
+
+echo "Done remote script"
+END_SCRIPT
 
 echo "Done"
