improve deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -5,9 +5,32 @@ if [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ]; then
     exit 1
 fi
 
+# the local directory where the site is built
+src="./site/.vitepress/dist"
+if [ ! -d "$src" ]; then
+    echo "Error: $src does not exist"
+    exit 1
+fi
+
+# the site's base directory on the server
+site_dir="/var/www/www.popclip.app"
+
+# check that the git repo is clean
+if [ -n "$(git status --porcelain)" ]; then
+    echo "Error: git repo is not clean"
+    exit 1
+fi
+
+# we use the git commit hash to generate a unique folder name
 id="g$(git rev-parse HEAD | cut -c 1-11)"
-dest="/var/www/www.popclip.app"
-echo "Sending files to ${SSH_USER}@${SSH_HOST}:$dest/${id}/"
-rsync -avz "./site/.vitepress/dist/" "${SSH_USER}@${SSH_HOST}:$dest/${id}/"
-echo "Setting symlink to ${id}"
-ssh ${SSH_USER}@${SSH_HOST} "cd $dest && ln -s -f ${id} static"
+
+# the full destination path
+dest="${SSH_USER}@${SSH_HOST}:$site_dir/${id}/"
+echo "Sending files to ${dest}"
+rsync -avz "${src}/" "${dest}"
+
+# symlink the new folder so it gets served
+echo "Updating symlink"
+ssh ${SSH_USER}@${SSH_HOST} "cd ${site_dir} && ln -s -f ${id} static"
+
+echo "Done"
